### ISSUE TITLE
Simplified approach (?)

### ISSUE THREAD

**Issue by ditman** [koichia/flutter_web_file_selector#1]
Have you considered something like this for the markup of the HtmlElementView? I think this might be simpler, but I haven't tested it in mobile :/

https://jsfiddle.net/ditman/xcLbuap9

Thanks for creating this! It's amazing!

**Comment by koichia** [comment]
Thanks for your suggestion! Yes that is indeed simpler (I can remove the extra button). I modified the code and tried it just now on iOS and Android and it did work just fine on both of them so I should go ahead and update the code 🙂

**Comment by koichia** [comment]
I noticed that I also forgot to set cursor to pointer. So I went ahead and added it in, and then I encountered a bit of a hiccup. It looks like the cursor does not change when hovered over a specific portion of &lt;input type="file"&gt; 🤔

Below are examples in jsfiddle, with &lt;input&gt; set to opacity of 0.5:

Chrome & Edge: Cursor doesn't change when cursor is over the "Choose File" button (changes everywhere else).
![chrome-cursor](https://github.com/koichia/flutter_web_file_selector/assets/2694983/ae2efe77-ce33-4b85-8908-750d6b8148a4)

Firefox: Cursor doesn't change when cursor is over the file name (or "No file selected") text (changes everywhere else).
![firefox-cursor](https://github.com/koichia/flutter_web_file_selector/assets/2694983/38c742c1-251a-4601-ab1c-be001a26fbf0)

This doesn't seem to happen with &lt;button&gt; so for now I should keep it (but I will add cursor: pointer).

**Comment by ditman** [comment]
Woops! I tweaked the code a little bit so it uses label and a display:none input:

https://jsfiddle.net/ditman/xcLbuap9/

(Not sure with display:none where the mobile browsers will attach the popup though!)

**Comment by koichia** [comment]
That's brilliant! I did not think of using the label here. I'll try this out. Thank you! 🙂

**Comment by koichia** [comment]
Yes it did work on mobile browsers just fine (on both iOS and Android) so I went ahead with the modifications and then created a new package.

Also, this is not a new issue, but I found that on mobile Chrome it was applying its own highlight color when tapped, so I used `-webkit-tap-highlight-color` to prevent that.

https://github.com/koichia/flutter_web_file_selector/blob/68f7d0d67b1916395bfde2bc5bc1313752b4bc98/lib/src/flutter_web_file_selector_platform_view_web.dart#L162-L165
